[settings]
experimental = true
lockfile = true
disable_backends = [
    "asdf",
    "vfox",
]

[tools]
python = "latest"
uv = "latest"
lychee = "latest"

[hooks]
enter = "mise install --quiet --locked"

[[watch_files]]
patterns = ["mise.toml", "mise.lock"]
run = "mise install --quiet --locked"

[tasks.check-links]
description = "Check links with lychee"
run = "lychee --no-progress './**/*.md' './**/*.rst' './src/**/*.py' './pyproject.toml'"
